name: Check API Status V3
 
on:
  workflow_dispatch:
    #types: [manual-trigger]
 
jobs:
  check_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Status
        id: api_status
        run: |
          response=$(curl -s -o /dev/null -w -u "servicenowint25.im:${{ secrets.servicenowint25 }}" https://pgglobalenterprise.service-now.com/api/now/table/incident?sysparm_query=assignment_group=2483d38f4fab22004679cf5d0210c7f3&assigned_to=&state=1)
          echo ${response}

