name: Check API Status V3
 
on:
  workflow_dispatch:
    #types: [manual-trigger]
 
jobs:
  check_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Status
        id: api_status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://137.181.80.140:6330)
          echo ${response}

